# platform specific definitions
include arch/mips/Kbuild.platforms
obj-y := $(platform-y)

# make clean traverses $(obj-) without having included .config, so
# everything ends up here
obj- := $(platform-)

# mips object files
# The object files are linked as core-y files would be linked

obj-y += kernel/
obj-y += mm/
obj-y += net/
obj-y += vdso/

ifdef CONFIG_KVM
obj-y += kvm/
endif
