#!/bin/bash -eu

# autopkgtest checks for a non-zero exit code *or* any output to
# stderr.  So we should continue after a failure, but make sure
# something is written to stderr.

echo "I: Running debian_linux.debian unit tests..."
# unittest only writes to stderr
if ! PYTHONPATH=debian/lib/python python3 -m debian_linux.debian 2>&1; then
    echo >&2 "E: some unit tests failed"
fi
