PROGS = x86_energy_perf_policy

installdir = /usr/sbin

include $(top_rulesdir)/Makefile.inc

CPPFLAGS += -I"$(top_srcdir)/tools/include" -DMSRHEADER='"$(top_srcdir)/arch/x86/include/asm/msr-index.h"'
